config/routes.rb
Rails.application.routes.draw do
  root to: 'campaigns#index'

  # While this definitely would work, I would be a little cautious about having so many nested resources. Usually
  # The rule of thumb is having two nested resources. I think you could achieve the same functionality without as many being nested
  resources :campaigns do
    resources :characters do
      resource :ability
      resources :spells
    end
    resource :dmaster
    resources :adventures
  end
end

app/models/character.rb
class Character < ActiveRecord::Base
  belongs_to :campaign
  has_one :ability, dependent: :destroy
  has_many :spells, dependent: :destroy

  validates :char_name, presence: true
  validates :klass, presence: true
  validates :level, presence: true
  validates :race, presence: true
  validates :xp, presence: true
  validates :hp_max, presence: true
  validates :hp_current, presence: true
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  def index
    @campaign = Campaign.find(params[:campaign_id])
    @characters = @campaign.characters.all.order(:id)
  end

  def show
    @campaign = Campaign.find(params[:campaign_id])
    @character = Character.find(params[:id])
  end

  def new
    @campaign = Campaign.find(params[:campaign_id])
    @character = Character.new
  end

  def create
    @campaign = Campaign.find(params[:campaign_id])
    @character = @campaign.characters.create! character_params

    redirect_to campaign_character_path(@campaign, @character)
  end

  def edit
    @campaign = Campaign.find(params[:campaign_id])
    @character = Character.find(params[:id])
  end

  def update
    @campaign = Campaign.find(params[:campaign_id])
    @character = Character.find(params[:id])
    @character.update character_params

    redirect_to campaign_character_path(@campaign, @character)
  end

  def destroy
    @campaign = Campaign.find(params[:campaign_id])
    @character = Character.find(params[:id])
    @character.destroy

    redirect_to campaign_path(@campaign)
  end

  private
  def character_params
    params.require(:character).permit(:player_name, :char_name, :klass, :level, :race, :background, :alignment, :archetype, :xp, :hp_max, :hp_current, :armor_class, :initiative, :speed, :prof_bonus, :inspiration, :languages, :features, :equipment, :personality, :ideals, :bonds, :flaws, :img_url)
  end

  # You could do something similar here:
  # because you use the following two lines throughout your enitre controller
  # you could write the following:
  # def set_campaign
  #   @campaign = Campaign.find(params[:campaign_id])
  # end
  # then at top:
  # before_action :set_campaign
  # this is define @campaign before each restful action/method

end

app/views/characters/edit.html.erb
<%= render "layouts/logo" %>
<div id="back" class="emphasis"><%= link_to "Back to Campaign", campaign_path(@campaign) %></div>
<!--As mentioned in dmasters edit.html.erb view, I would definitlely put this form into a partial then call render on it here and in new.html.erb -->
<h2 id="title">Edit Character:</h2>
<div class="container">
<%= form_for [@campaign, @character] do |f| %>
<div class="col-sm-4 col-sm-offset-1">
  <div><%= f.label :title, "Character Name:" %></div>
  <div><%= f.text_field :char_name %></div>
  <div><%= f.label :title, "Player Name:" %></div>
  <div><%= f.text_field :player_name %></div>
  <div><%= f.label :title, "Image of Player (.jpg, .png):" %></div>
  <div><%= f.text_field :img_url %></div>
  <div><%= f.label :title, "Level:" %></div>
  <div><%= f.text_field :level %></div>
  <div><%= f.label :title, "Class:" %></div>
  <div><%= f.select :klass, ['Barbarian', 'Bard', 'Cleric', 'Druid', 'Fighter', 'Wizard', 'Monk', 'Paladin', 'Ranger', 'Sorcerer', 'Rogue', 'Warlock']%></div>
  <div><%= f.label :title, "Race:" %></div>
  <div><%= f.select :race, ['Elf', 'Dwarf', 'Halfling', 'Human'] %></div>
  <div><%= f.label :title, "Background:" %></div>
  <div><%= f.select :background, ['Noble', 'Soldier', 'Acolyte', 'Criminal', 'Sage', 'Folk Hero', 'Spy'] %></div>
  <div><%= f.label :title, "Alignment:" %></div>
  <div><%= f.select :alignment, ['Lawful Good', 'Neutral Good', 'Chaotic Good', 'Lawful Neutral', 'Neutral', 'Chaotic Neutral', 'Lawful Evil', 'Neutral Evil', 'Chaotic Evil'] %></div>
  <div><%= f.label :title, "Archetype (Level 3+):" %></div>
  <div><%= f.text_field :archetype %></div>
  <div><%= f.label :title, "XP:" %></div>
  <div><%= f.text_field :xp %></div>
  <div><%= f.label :title, "Max HP:" %></div>
  <div><%= f.text_field :hp_max %></div>
  <div><%= f.label :title, "Current HP:" %></div>
  <div><%= f.text_field :hp_current %></div>
  <div><%= f.label :title, "Armor Class:" %></div>
  <div><%= f.text_field :armor_class %></div>
  <div><%= f.label :title, "Initiative:" %></div>
  <div><%= f.text_field :initiative %></div>
  <div><%= f.label :title, "Speed:" %></div>
  <div><%= f.text_field :speed %></div>
  <div><%= f.label :title, "Inspiration:" %></div>
  <div><%= f.text_field :inspiration %></div>
</div>
<div class="col-sm-4 col-sm-offset-1">
  <div><%= f.label :title, "Proficiency Bonus:" %></div>
  <div><%= f.text_field :prof_bonus %></div>
  <div><%= f.label :title, "Languages:" %></div>
  <div><%= f.text_area :languages, :cols => "24", :rows => "4" %></div>
  <div><%= f.label :title, "Feautures:" %></div>
  <div><%= f.text_area :features, :cols => "24", :rows => "4" %></div>
  <div><%= f.label :title, "Equipment:" %></div>
  <div><%= f.text_area :equipment, :cols => "24", :rows => "4" %></div>
  <div><%= f.label :title, "Personality:" %></div>
  <div><%= f.text_area :personality, :cols => "24", :rows => "4" %></div>
  <div><%= f.label :title, "Ideals:" %></div>
  <div><%= f.text_area :ideals, :cols => "24", :rows => "4" %></div>
  <div><%= f.label :title, "Bonds:" %></div>
  <div><%= f.text_area :bonds, :cols => "24", :rows => "4" %></div>
  <div><%= f.label :title, "Flaws:" %></div>
  <div><%= f.text_area :flaws, :cols => "24", :rows => "4" %></div>
  <div><%= f.submit "Save Changes" %></div>
<% end %>

</div>
</div>

app/views/characters/new.html.erb
<%= render "layouts/logo" %>
<div id="back" class="emphasis"><%= link_to "Back to Campaign", campaign_path(@campaign) %></div>

<h2 id="title">Make a New Character:</h2>
<div class="container">
<%= form_for [@campaign, @character] do |f| %>
<div class="col-sm-4 col-sm-offset-1">
  <div><%= f.label :title, "Character Name:" %></div>
  <div><%= f.text_field :char_name %></div>
  <div><%= f.label :title, "Player Name:" %></div>
  <div><%= f.text_field :player_name %></div>
  <div><%= f.label :title, "Image of Player (.jpg, .png):" %></div>
  <div><%= f.text_field :img_url %></div>
  <div><%= f.label :title, "Level:" %></div>
  <div><%= f.text_field :level %></div>
  <div><%= f.label :title, "Class:" %></div>
  <div><%= f.select :klass, ['Barbarian', 'Bard', 'Cleric', 'Druid', 'Fighter', 'Wizard', 'Monk', 'Paladin', 'Ranger', 'Sorcerer', 'Rogue', 'Warlock']%></div>
  <div><%= f.label :title, "Race:" %></div>
  <div><%= f.select :race, ['Elf', 'Dwarf', 'Halfling', 'Human'] %></div>
  <div><%= f.label :title, "Background:" %></div>
  <div><%= f.select :background, ['Noble', 'Soldier', 'Acolyte', 'Criminal', 'Sage', 'Folk Hero', 'Spy'] %></div>
  <div><%= f.label :title, "Alignment:" %></div>
  <div><%= f.select :alignment, ['Lawful Good', 'Neutral Good', 'Chaotic Good', 'Lawful Neutral', 'Neutral', 'Chaotic Neutral', 'Lawful Evil', 'Neutral Evil', 'Chaotic Evil'] %></div>
  <div><%= f.label :title, "Archetype (Level 3+):" %></div>
  <div><%= f.text_field :archetype %></div>
  <div><%= f.label :title, "XP:" %></div>
  <div><%= f.text_field :xp %></div>
  <div><%= f.label :title, "Max HP:" %></div>
  <div><%= f.text_field :hp_max %></div>
  <div><%= f.label :title, "Current HP:" %></div>
  <div><%= f.text_field :hp_current %></div>
  <div><%= f.label :title, "Armor Class:" %></div>
  <div><%= f.text_field :armor_class %></div>
  <div><%= f.label :title, "Initiative:" %></div>
  <div><%= f.text_field :initiative %></div>
  <div><%= f.label :title, "Speed:" %></div>
  <div><%= f.text_field :speed %></div>
  <div><%= f.label :title, "Inspiration:" %></div>
  <div><%= f.text_field :inspiration %></div>
  </div>
  <div class="col-sm-4 col-sm-offset-1">
  <div><%= f.label :title, "Proficiency Bonus:" %></div>
  <div><%= f.text_field :prof_bonus %></div>
  <div><%= f.label :title, "Languages:" %></div>
  <div><%= f.text_area :languages, :cols => "24", :rows => "4" %></div>
  <div><%= f.label :title, "Feautures:" %></div>
  <div><%= f.text_area :features, :cols => "24", :rows => "4" %></div>
  <div><%= f.label :title, "Equipment:" %></div>
  <div><%= f.text_area :equipment, :cols => "24", :rows => "4" %></div>
  <div><%= f.label :title, "Personality:" %></div>
  <div><%= f.text_area :personality, :cols => "24", :rows => "4" %></div>
  <div><%= f.label :title, "Ideals:" %></div>
  <div><%= f.text_area :ideals, :cols => "24", :rows => "4" %></div>
  <div><%= f.label :title, "Bonds:" %></div>
  <div><%= f.text_area :bonds, :cols => "24", :rows => "4" %></div>
  <div><%= f.label :title, "Flaws:" %></div>
  <div><%= f.text_area :flaws, :cols => "24", :rows => "4" %></div>
  <div><%= f.submit "Create" %></div>
</div>
<% end %>
</div>

app/views/characters/show.html.erb
<%= render "layouts/logo" %>
<div id="back" class="emphasis"><%= link_to "Back to Campaign", campaign_path(@campaign) %></div>

<h2 id="charName"><%= @character.char_name %></h2>
  <div><img class="float" src="<%= @character.img_url %>"/></div>
  <div><span class="emphasis">Updated At: </span><%= @character.updated_at %></div>
  <div><span class="emphasis">Player Name: </span><%= @character.player_name %></div>
  <div><span class="emphasis">Class: </span><%= @character.klass.capitalize %></div>
  <div><span class="emphasis">Level: </span><%= @character.level %></div>
  <div><span class="emphasis">Race: </span><%= @character.race %></div>
  <div><span class="emphasis">Background: </span><%= @character.background %></div>
  <div><span class="emphasis">Alignment: </span><%= @character.alignment %></div>
  <div><span class="emphasis">Archetype (Level 3+): </span><%= @character.archetype %></div>
  <div><span class="emphasis">XP: </span><%= @character.xp %></div>
  <div><span class="emphasis">Max HP: </span><%= @character.hp_max %></div>
  <div><span class="emphasis">Current HP: </span><%= @character.hp_current %></div>
  <div><span class="emphasis">Armor Class: </span><%= @character.armor_class %></div>
  <div><span class="emphasis">Initiative: </span>+<%= @character.initiative %></div>
  <div><span class="emphasis">Speed: </span><%= @character.speed %></div>
  <div><span class="emphasis">Proficieny Bonus: </span>+<%= @character.prof_bonus %></div>
  <div><span class="emphasis">Inspiration: </span>+<%= @character.inspiration %></div>
  <div><span class="emphasis">Languages: </span><%= @character.languages %></div>
  <div><span class="emphasis">Features: </span><%= @character.features %></div>
  <div><span class="emphasis">Equipment: </span><%= @character.equipment %></div>
  <div><span class="emphasis">Personality: </span><%= @character.personality %></div>
  <div><span class="emphasis">Ideals: </span><%= @character.ideals %></div>
  <div><span class="emphasis">Bonds: </span><%= @character.bonds %></div>
  <div><span class="emphasis">Flaws: </span><%= @character.flaws %></div>
<button class="makeButton"><%= link_to "Edit", edit_campaign_character_path(@campaign, @character ) %></button>
<h2>Abilities &amp; Skills</h2>
<% if @character.ability %>
<div class="container">
  <div class="col-sm-6">
    <div><span class="emphasis">Strength: </span><%= @character.ability.strength %></div>
    <div><span class="emphasis">Strength Modifier: </span><%= @character.ability.strength_mod %></div>
    <div><span class="emphasis">Dexterity: </span><%= @character.ability.dexterity %></div>
    <div><span class="emphasis">Dexterity Modifier: </span><%= @character.ability.dexterity_mod %></div>
    <div><span class="emphasis">Constitution: </span><%= @character.ability.constitution %></div>
    <div><span class="emphasis">Constitution Modifier: </span><%= @character.ability.constitution_mod %></div>
    <div><span class="emphasis">Intelligence: </span><%= @character.ability.intelligence %></div>
    <div><span class="emphasis">Intelligence Modifier: </span><%= @character.ability.intelligence_mod %></div>
    <div><span class="emphasis">Wisdom: </span><%= @character.ability.wisdom %></div>
    <div><span class="emphasis">Wisdom Modifier: </span><%= @character.ability.wisdom_mod %></div>
    <div><span class="emphasis">Charisma: </span><%= @character.ability.charisma %></div>
    <div><span class="emphasis">Charisma Modifier: </span><%= @character.ability.charisma_mod %></div>
  </br>
    <div><p>Use your ability modifiers to complete your skills! Don't forget to add the value of your proficiency bonus to your designated proficient skills.</p></div>
  </div>
  <div class="col-sm-6">
    <div><span class="emphasis">Acrobatics (Dex): </span><%= @character.ability.acrobatics %></div>
    <div><span class="emphasis">Animal Handling (Wis): </span><%= @character.ability.animal_handling %></div>
    <div><span class="emphasis">Arcana (Int): </span><%= @character.ability.arcana %></div>
    <div><span class="emphasis">Athletics (Str): </span><%= @character.ability.athletics %></div>
    <div><span class="emphasis">Deception (Cha): </span><%= @character.ability.deception %></div>
    <div><span class="emphasis">History (Int): </span><%= @character.ability.history %></div>
    <div><span class="emphasis">Insight (Wis): </span><%= @character.ability.insight %></div>
    <div><span class="emphasis">Intimidation (Cha): </span><%= @character.ability.intimidation %></div>
    <div><span class="emphasis">Investigation (Int): </span><%= @character.ability.investigation %></div>
    <div><span class="emphasis">Medicine (Wis): </span><%= @character.ability.medicine %></div>
    <div><span class="emphasis">Nature (Int): </span><%= @character.ability.nature %></div>
    <div><span class="emphasis">Perception (Wis): </span><%= @character.ability.perception %></div>
    <div><span class="emphasis">Performance (Cha): </span><%= @character.ability.performance %></div>
    <div><span class="emphasis">Persuasion (Cha): </span><%= @character.ability.persuasion %></div>
    <div><span class="emphasis">Religion (Int): </span><%= @character.ability.religion %></div>
    <div><span class="emphasis">Sleight of Hand (Dex): </span><%= @character.ability.sleight_hand %></div>
    <div><span class="emphasis">Stealth (Dex): </span><%= @character.ability.stealth %></div>
    <div><span class="emphasis">Survival (Wis): </span><%= @character.ability.survival %></div>
    <div><span class="emphasis">Passive Wisdom (Perception): </span><%= @character.ability.perception %></div>
  </div>
</div>
<button class="makeButton"><%= link_to "Edit", edit_campaign_character_ability_path( @campaign, @character ) %></button>
<% else %>
<button class="makeButton"><%= link_to "Add", new_campaign_character_ability_path( @campaign, @character ) %></button>
<% end %>

<h2>Spells <%= link_to "(+)", new_campaign_character_spell_path( @campaign , @character) %></h2>
<div class="campaigns">
  <% @character.spells.each do |spell| %>
    <div class="campItem"><h4 class="emphasis"><%= link_to "#{spell.name}", campaign_character_spell_path( @campaign, @character, spell ) %></h4>
      <div><%= spell.description %></div>
      <div><button class="makeButton"><%= link_to "Edit", edit_campaign_character_spell_path( @campaign, @character, spell ) %></button></div>
      <div><%= form_for [@campaign, @character, spell], method: :delete do |f| %>
        <%= f.submit "Delete", class: "delete" %>
      <% end %></div>
    </div>
  <% end %>
</div>