config/routes.rb
Rails.application.routes.draw do
  root to: 'campaigns#index'

  # While this definitely would work, I would be a little cautious about having so many nested resources. Usually
  # The rule of thumb is having two nested resources. I think you could achieve the same functionality without as many being nested
  resources :campaigns do
    resources :characters do
      resource :ability
      resources :spells
    end
    resource :dmaster
    resources :adventures
  end
end

app/models/campaign.rb
class Campaign < ActiveRecord::Base
  # this is great putting dependent: :destroy
  has_many :characters, dependent: :destroy
  has_one :dmaster, dependent: :destroy
  has_many :adventures, dependent: :destroy

  validates :name, presence: true
end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
  def index
    @campaigns = Campaign.all.order(:id)
  end

  def show
    @campaign = Campaign.find(params[:id])
  end

  def new
    @campaign = Campaign.new
  end

  def create
    @campaign = Campaign.create! campaign_params

    redirect_to campaign_path(@campaign)
  end

  def edit
    @campaign = Campaign.find(params[:id])
  end

  def update
    @campaign = Campaign.find(params[:id])
    @campaign.update campaign_params

    redirect_to campaign_path(@campaign)
  end

  def destroy
    @campaign = Campaign.find(params[:id])
    @campaign.destroy

    redirect_to campaigns_path
  end

  private
  def campaign_params
    params.require(:campaign).permit(:name, :img_url, :summary)
  end

end

app/views/campaigns/edit.html.erb
<!--Awesome job here rendering the layout or logo! Any reasion you did not directly put it in the application.html.erb file?-->
<%= render "layouts/logo" %>
<div id="back" class="emphasis"><%= link_to "Back to Campaign", campaign_path %></div>

<h2>Edit Campaign:</h2>
<%= form_for @campaign do |f| %>
  <div><%= f.label :title, "Campaign Name:" %></div>
  <div><%= f.text_field :name %></div>
  <div><%= f.label :title, "Image of Map (.jpg, .png):" %></div>
  <div><%= f.text_field :img_url %></div>
  <div><%= f.label :title, "Short Summary:" %></div>
  <div><%= f.text_area :summary, :cols => "24", :rows => "4"  %></div>

  <div><%= f.submit "Save Changes" %></div>
<% end %>

app/views/campaigns/index.html.erb
<!-- Carousel
    ================================================== -->
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
      <!-- Indicators -->
      <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
      </ol>
      <div class="carousel-inner" role="listbox">
        <div class="item active">
          <img class="first-slide" src="http://dnd.wizards.com/sites/default/files/media/styles/story_banner/public/images/head-banner/HERO_RiseTiamat_1.jpg?itok=ou0OG0JI" alt="First slide">
          <div class="container">
            <div class="carousel-caption">
              <h1 id="mainName">d&amp;dr</h1>
              <p><a class="btn btn-md btn-primary" href="/campaigns/new" role="button">Create a Campaign Today</a></p>
            </div>
          </div>
        </div>
        <div class="item">
          <img class="second-slide" src="http://dnd.wizards.com/sites/default/files/media/styles/second_hubpage_banner/public/images/head-banner/03_NEW-TO-DnD_Races_Heroes_Hero_140725.jpg?itok=Lv71J5AL" alt="Second slide">
          <div class="container">
            <div class="carousel-caption">
              <h1 class="banner">Gather your friends.</h1>
              <p><a class="btn btn-md btn-primary" href="/campaigns/new" role="button">Create a Campaign Today</a></p>
            </div>
          </div>
        </div>
        <div class="item">
          <img class="third-slide" src="http://dnd.wizards.com/sites/default/files/media/styles/story_banner/public/images/head-banner/04-PRODUCT-INFO_Tabletop_Hero_PHB.jpg?itok=TGsc04Ek" alt="Third slide">
          <div class="container">
            <div class="carousel-caption">
              <h1 class="banner">Battle your foes.</h1>
              <p><a class="btn btn-md btn-primary" href="/campaigns/new" role="button">Create a Campaign Today</a></p>
            </div>
          </div>
        </div>
      </div>
      <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>

<h1 id="title">Campaigns <%= link_to "(+)", new_campaign_path %></h1>
<div class="campaigns">
  <% @campaigns.each do |campaign| %>
    <div class="campItem"><div class="emphasis campaignName"><%= link_to campaign.name, campaign %></div>
    <div><%= campaign.summary %></div>
    </div>
  <% end %>
</div>

app/views/campaigns/new.html.erb
<%= render "layouts/logo" %>
<div id="back" class="emphasis"><%= link_to "Back to Campaigns", campaigns_path %></div>

<h2>Make a New Campaign:</h2>
<%= form_for @campaign do |f| %>
  <div><%= f.label :title, "Campaign Name:" %></div>
  <div><%= f.text_field :name %></div>
  <div><%= f.label :title, "Image of Map (.jpg, .png):" %></div>
  <div><%= f.text_field :img_url %></div>
  <div><%= f.label :title, "Short Summary:" %></div>
  <div><%= f.text_area :summary, :cols => "24", :rows => "4"  %></div>

  <div><%= f.submit "Create" %></div>
<% end %>

app/views/campaigns/show.html.erb
<% if @campaign.img_url == "" %>
  <%= render "layouts/logo" %>
  <div id="back" class="emphasis"><%= link_to "Back to Campaigns", campaigns_path %></div>
  <h1 id="title"><%=@campaign.name%></h1>
<% elsif @campaign.img_url %>
  <div id="myCarousel" class="carousel">
    <div class="carousel-inner" role="listbox">
      <div class="item active">
        <img id="map" src="<%= @campaign.img_url %>">
        <div class="container">
          <div class="carousel-caption" id="title">
            <h1><%= @campaign.name %></h1>
          </div>
        </div>
      </div>
    </div>
    <div id="back" class="emphasis"><%= link_to "Back to Campaigns", campaigns_path %></div>
  </div>
<% else %>
<%= render "layouts/logo" %>
  <div id="back" class="emphasis"><%= link_to "Back to Campaigns", campaigns_path %></div>
  <h1 id="title"><%=@campaign.name%></h1>
<% end %>


  <div class="container">
    <div class="col-sm-4 col-sm-offset-1">
    <h3><%= @campaign.name %></h3>
    <div><span class="emphasis">Updated At: </span><%= @campaign.updated_at %></div>
    <div><%= @campaign.summary %></div>
    <h4 class="emphasis"><%= link_to "Map", @campaign.img_url %></h4>
    <button class="makeButton"><%= link_to "Edit Campaign", edit_campaign_path( @campaign ) %></button>

    <%= form_for @campaign, method: :delete do |f| %>
      <%= f.submit "Delete Entire Campaign", class: "delete" %>
    <% end %>
    </div>
    <div class="col-sm-4 col-sm-offset-1">
    <% if @campaign.dmaster %>
      <h3>Dungeon Master</h3>
        <h4 class="emphasis"><%= link_to "#{@campaign.dmaster.name}", campaign_dmaster_path(@campaign, @campaign.dmaster) %></h4>
        <div><button class="makeButton"><%= link_to "Edit", edit_campaign_dmaster_path( @campaign, @campaign.dmaster ) %></button></div>
    <% else %>
      <h3>Dungeon Master<%= link_to "(+)", new_campaign_dmaster_path( @campaign ) %></h3>
    <% end %>
  </div>
  </div>

</br>
<div class="container">
  <div class="col-sm-4 col-sm-offset-1">
  <h3>Characters <%= link_to "(+)", new_campaign_character_path( @campaign ) %></h3>
    <% @campaign.characters.each do |character| %>
        <h4 class="emphasis"><%= link_to "#{character.char_name}", campaign_character_path( @campaign, character ) %></h4>
        <h5><%= character.player_name %></h5>
        <div><button class="makeButton"><%= link_to "Edit", edit_campaign_character_path( @campaign, character ) %></button></div>
        <div><%= form_for [@campaign, character], method: :delete do |f| %>
          <%= f.submit "Delete", class: "delete" %>
        <% end %></div>
    <% end %>
  </div>
  <div class="col-sm-4 col-sm-offset-1">
    <h3>Adventures <%= link_to "(+)", new_campaign_adventure_path( @campaign ) %></h3>
      <% @campaign.adventures.each do |adventure| %>
          <h4 class="emphasis"><%= link_to "#{adventure.name}", campaign_adventure_path( @campaign, adventure ) %></h4>
          <div><button class="makeButton"><%= link_to "Edit", edit_campaign_adventure_path( @campaign, adventure ) %></button></div>
          <div><%= form_for [@campaign, adventure], method: :delete do |f| %>
            <%= f.submit "Delete", class: "delete" %>
          <% end %></div>
      <% end %>
  </div>
</div>